build:
  environment:
    node: v18.0.0

  nodes:
    coverage:
      tests:
        override:
          - npm ci
          - npm test
          - command: ./my-test-run
            coverage:
              file: coverage/lcov.info
              format: lcov
