build:
  environment:
    node: v18.0.0

  nodes:
    analysis:
      project_setup:
        override: true
        commands:
          - 'npm ci'
          - 'npm test'
          - 'npm run coverage'

  cache:
    directories:
      - node_modules/
